version: '3.8'

services:
  php_app:
    build: .
    container_name: php_app
    ports:
      - "8081:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crud_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:


